name: PR build

on:
  pull_request:
    branches:
      - master

permissions:
  security-events: write  # required for CodeQL
  packages: read
  contents: read
  actions: read

jobs:
  build:
    uses: ./.github/workflows/main.yml
